version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    open-pull-requests-limit: 5
    reviewers:
      - "TheLinuxITGuy"
    assignees:
      - "TheLinuxITGuy"
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "cargo"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "main"
    reviewers:
      - "TheLinuxITGuy"
    assignees:
      - "TheLinuxITGuy"
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
      include: "scope"
